language: generic
sudo: false

git:
  submodules: false

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'


install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack test --coverage --no-terminal
- stack install hpc-coveralls

after_script:
- mkdir dist
- "mv `stack path | grep 'local-install-root:' | cut -d: -f2`/hpc dist"
- mv dist/hpc/DeepDarkFantasy dist/hpc/tix
- mv dist/hpc/combined/all dist/hpc/mix
- cd dist/hpc/mix
- for i in Deep*; do mv $i tmp; mkdir $i; mv tmp $i/$i;done
- find . -type f -name '*.mix' -print0 | xargs -0 rename 's/(.mix)$//'
- cd ../../../
- hpc-coveralls TestPE TestPoly TestXor
- find dist/hpc
